codecov:
  token: ${{ secrets.CODECOV_TOKEN }}
  coverage:
    range: '80...100'
    status:
      project:
        default:
          target: 80%
          base: auto
          branches:
            - master
            - SE*
            - feature*
            - hotfix*
            - fix*
      tests:
        target: 80%
        paths:
          - 'tests/'
      app:
        paths: '!tests/'
  comment:
    layout: 'reach, diff, flags, files, tree, betaprofilig'
    behavior: default
    require_changes: false
    require_base: no
    require_head: no
    show_crtitical_paths: true
    branches:
      - master
      - SE*
      - feature*
      - hotfix*
      - fix*
