[tool.black]
skip-string-normalization=true
line-length=120
exclude = '''
/(
  | app/migrations
)/
'''

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
ignore_missing_imports = true
exclude = ['app/migrations/','tests/']

[tool.isort]
skip = ["cdk/app.py", "app/migrations/"]